/**
 * Move Generation Logic
 *
 * Transforms ranked concept nodes into typed PlannedMove objects.
 * Each concept gets one move type based on its learning status:
 *
 *   review    — concept has flashcards due for review
 *   deepdive  — concept has related posts to explore
 *   connection — concept has related nodes to connect
 *   podcast   — weak area; AI podcast would reinforce it
 */

import type { Question, TrajectorySignal, PlannedMove, PlannedMoveType } from '../types';
import { flashcardService } from './flashcard.service';
import { today } from '../lib/date';

// ── Move type determination ────────────────────────────────────────────────

function decideMoveType(concept: Question, signals: TrajectorySignal): PlannedMoveType {
  // If it's a weak area, suggest a podcast to deepen understanding.
  if (signals.weakAreas.includes(concept.id)) return 'podcast';

  // If flashcard is due or concept hasn't been reviewed recently, suggest review.
  const allCards = flashcardService.getAll();
  const conceptCards = allCards.filter((c) => c.nodeId === concept.id);
  const hasDueCard = conceptCards.some((c) => c.reviewSchedule.nextReviewDate <= today());
  if (hasDueCard) return 'review';

  // If concept has related nodes, suggest exploring connections.
  if (concept.relatedQuestionIds.length > 0) return 'connection';

  // Otherwise suggest a deep dive via the feed post.
  return 'deepdive';
}

// ── Reason generation ──────────────────────────────────────────────────────

function buildReason(
  moveType: PlannedMoveType,
  concept: Question,
  score: number,
): string {
  const daysSinceReview = concept.lastReviewedAt
    ? Math.round((Date.now() - concept.lastReviewedAt) / (24 * 60 * 60 * 1000))
    : null;

  switch (moveType) {
    case 'review':
      return daysSinceReview !== null && daysSinceReview > 0
        ? `Time to review: ${daysSinceReview} day${daysSinceReview !== 1 ? 's' : ''} ago`
        : 'Flashcard due for review';
    case 'deepdive':
      return score >= 70
        ? 'High relevance to your current learning path'
        : 'Explore this concept further';
    case 'connection':
      return `${concept.relatedQuestionIds.length} related concept${concept.relatedQuestionIds.length !== 1 ? 's' : ''} to connect`;
    case 'podcast':
      return 'This area needs reinforcement — listen to solidify';
  }
}

// ── Time estimates ─────────────────────────────────────────────────────────

const MOVE_TIME_MS: Record<PlannedMoveType, number> = {
  review: 5 * 60 * 1000,       // 5 min
  deepdive: 10 * 60 * 1000,    // 10 min
  connection: 7 * 60 * 1000,   // 7 min
  podcast: 15 * 60 * 1000,     // 15 min
};

// ── Linked resource ────────────────────────────────────────────────────────

function buildLinkedResource(
  moveType: PlannedMoveType,
  concept: Question,
): PlannedMove['linkedResource'] {
  switch (moveType) {
    case 'review':
      return { type: 'review', id: concept.id };
    case 'deepdive':
      return { type: 'post', id: concept.id };
    case 'connection':
      return { type: 'question', id: concept.id };
    case 'podcast':
      return { type: 'question', id: concept.id };
  }
}

// ── ID generation ──────────────────────────────────────────────────────────

let idCounter = 0;
function newMoveId(): string {
  return `move-${Date.now()}-${++idCounter}`;
}

// ── Public API ─────────────────────────────────────────────────────────────

/**
 * Generate PlannedMove objects from a ranked list of concept nodes.
 *
 * @param rankedConcepts  - Output from `rankConcepts()`.
 * @param signals         - User trajectory (needed for reason text).
 * @returns               Array of PlannedMove ready for storage.
 */
export function generateMoves(
  rankedConcepts: Array<{ concept: Question; score: number }>,
  signals: TrajectorySignal,
): PlannedMove[] {
  const now = Date.now();

  return rankedConcepts.map(({ concept, score }) => {
    const moveType = decideMoveType(concept, signals);
    const reason = buildReason(moveType, concept, score);

    return {
      id: newMoveId(),
      title: concept.title ?? concept.summary ?? concept.content.slice(0, 60),
      conceptId: concept.id,
      keywords: concept.keywords.slice(0, 4),
      moveType,
      relevanceScore: score,
      reason,
      targetTime: MOVE_TIME_MS[moveType],
      linkedResource: buildLinkedResource(moveType, concept),
      isAutoGenerated: true,
      createdAt: now,
    };
  });
}
