/**
 * Phase 10: Move Generator Service
 * Converts scored concepts to PlannedMove objects with appropriate move types and linked resources.
 */

import type { TrajectorySignal, PlannedMove, MoveType } from '../types/planner';
import { questionService } from './question.service';
import { flashcardService } from './flashcard.service';
import { suggestionScorer } from './suggestionScorer.service';

// ─── Description map ──────────────────────────────────────────────────────

const REASON_MAP: Record<MoveType, string> = {
  review: 'Revisit this weak area to strengthen your recall.',
  deepdive: 'This topic keeps coming up — explore it in depth.',
  connection: 'This concept has multiple connections — map them out.',
  podcast: 'Listen to a podcast segment to reinforce this topic.',
};

// ─── ID counter ───────────────────────────────────────────────────────────

let idCounter = 0;

// ─── Service ──────────────────────────────────────────────────────────────

export const moveGenerator = {
  /**
   * Generate PlannedMove objects from a list of scored concept IDs.
   * Each move has a type, goal, linked resource, and relevance score.
   */
  generateMoves(conceptIds: string[], signals: TrajectorySignal): PlannedMove[] {
    const moves: PlannedMove[] = [];
    const now = Date.now();

    for (let index = 0; index < conceptIds.length; index++) {
      const conceptId = conceptIds[index];
      const concept = questionService.getAll().find(q => q.id === conceptId);
      if (!concept) continue; // skip missing concepts

      const score = suggestionScorer.scoreMove(conceptId, signals);

      // ── Determine move type ─────────────────────────────────────────
      let moveType: MoveType = 'review'; // default

      if (signals.weakAreas.includes(conceptId) && score > 70) {
        moveType = 'review'; // critical review for weak areas
      } else if ((concept.relatedQuestionIds?.length ?? 0) > 2) {
        moveType = 'connection'; // explore connections
      } else if (signals.questionFrequency > 3) {
        moveType = 'deepdive'; // deep dive into active topic
      }

      // ── Determine linked resource ───────────────────────────────────
      let linkedResource: PlannedMove['linkedResource'] | undefined;

      if (moveType === 'review') {
        const cardId = this._findReviewCardFor(conceptId);
        if (cardId) {
          linkedResource = { type: 'review', id: cardId };
        }
      } else if (moveType === 'connection') {
        const relatedId = concept.relatedQuestionIds?.[0];
        if (relatedId) {
          linkedResource = { type: 'question', id: relatedId };
        }
      } else if (moveType === 'deepdive') {
        const postId = this._findRelatedPost(conceptId);
        linkedResource = postId
          ? { type: 'post', id: postId }
          : { type: 'question', id: conceptId };
      }

      // ── Build PlannedMove object ────────────────────────────────────
      const icon = this._getMoveIcon(moveType);
      const title = concept.title ?? concept.content.slice(0, 50);

      const move: PlannedMove = {
        id: `move-${conceptId}-${now}-${++idCounter}`,
        type: 'retrieve',
        goal: `${icon} ${title}`,
        description: REASON_MAP[moveType],
        linkedConceptIds: [conceptId],
        status: 'suggested',
        createdAt: now,
        updatedAt: now,
        moveType,
        relevanceScore: score,
        linkedResource,
        isAutoGenerated: true,
      };

      moves.push(move);
    }

    return moves;
  },

  /** Return emoji icon for a move type. */
  _getMoveIcon(moveType: string): string {
    const icons: Record<string, string> = {
      review: '📚',
      deepdive: '🔗',
      connection: '🎯',
      podcast: '🎙️',
    };
    return icons[moveType] ?? '📝';
  },

  /** Find the flashcard ID for a given concept ID. Returns null if not found. */
  _findReviewCardFor(conceptId: string): string | null {
    const allCards = flashcardService.getAll();
    // Best effort: find a card whose session might relate to this concept
    const card = allCards.find(c =>
      c.sessionId.includes(conceptId) || conceptId.includes(c.sessionId),
    );
    return card ? card.id : null;
  },

  /** Find a related post ID for a given concept ID via conceptFeedService. Returns null if not found. */
  _findRelatedPost(_conceptId: string): string | null {
    // Future: query conceptFeedService for posts linked to this concept
    // For MVP: return null (post link is optional)
    return null;
  },
};
