/**
 * Planner Auto-Generation Service
 *
 * Orchestrates the full pipeline:
 *   1. Check trigger conditions (5+ KG nodes AND planner suggestions empty)
 *   2. Aggregate trajectory signals
 *   3. Score + rank concepts
 *   4. Generate PlannedMove objects
 *   5. Persist to localStorage + emit PLANNER_UPDATED
 *
 * Also handles daily refresh logic and duplicate suppression.
 */

import type { PlannedMove } from '../types';
import { questionService } from './question.service';
import { plannerService } from './planner.service';
import { trajectoryAnalyzerService } from './trajectoryAnalyzer.service';
import { rankConcepts } from './suggestionScorer.service';
import { generateMoves } from './moveGenerator.service';
import { eventBus } from '../lib/event-bus';

// ── Storage ────────────────────────────────────────────────────────────────

const MOVES_KEY = 'echolearn_planned_moves';
const LAST_REFRESH_KEY = 'echolearn_suggestions_last_refresh';

const DAILY_REFRESH_INTERVAL_MS = 24 * 60 * 60 * 1000; // 24 hours
const MIN_KG_NODES = 5;

function loadMoves(): PlannedMove[] {
  try {
    const raw = localStorage.getItem(MOVES_KEY);
    return raw ? (JSON.parse(raw) as PlannedMove[]) : [];
  } catch {
    return [];
  }
}

function saveMoves(moves: PlannedMove[]): void {
  try {
    localStorage.setItem(MOVES_KEY, JSON.stringify(moves));
  } catch { /* ignore storage errors */ }
}

function getLastRefreshTime(): number {
  try {
    const raw = localStorage.getItem(LAST_REFRESH_KEY);
    return raw ? parseInt(raw, 10) : 0;
  } catch {
    return 0;
  }
}

function setLastRefreshTime(ts: number): void {
  try {
    localStorage.setItem(LAST_REFRESH_KEY, String(ts));
  } catch { /* ignore */ }
}

// ── Dedup helper ───────────────────────────────────────────────────────────

/** Return true if a move for this conceptId was generated within the last 24h. */
function isRecentDuplicate(conceptId: string, existing: PlannedMove[]): boolean {
  const cutoff = Date.now() - DAILY_REFRESH_INTERVAL_MS;
  return existing.some(
    (m) => m.conceptId === conceptId && m.isAutoGenerated && m.createdAt > cutoff,
  );
}

// ── Core pipeline ──────────────────────────────────────────────────────────

export const plannerAutoGenService = {
  /**
   * Return true if auto-generation should run:
   *   - Knowledge graph has 5+ nodes, AND
   *   - Planner has no active or suggested chunks (is "empty")
   */
  shouldAutoGenerate(): boolean {
    const nodes = questionService.getAll();
    if (nodes.length < MIN_KG_NODES) return false;

    const { chunks } = plannerService.getAll();
    const activeOrSuggested = chunks.filter(
      (c) => c.status === 'suggested' || c.status === 'in_progress',
    );
    return activeOrSuggested.length === 0;
  },

  /**
   * Return true if a daily refresh is needed (last refresh > 24 hours ago).
   */
  isDailyRefreshNeeded(): boolean {
    return Date.now() - getLastRefreshTime() > DAILY_REFRESH_INTERVAL_MS;
  },

  /**
   * Load persisted PlannedMoves (auto-generated suggestions).
   */
  getMoves(): PlannedMove[] {
    return loadMoves().sort((a, b) => b.relevanceScore - a.relevanceScore);
  },

  /**
   * Run the full generation pipeline and persist results.
   * Skips concepts that already have a move created in the last 24h.
   */
  async generateAndStoreSuggestions(forceRefresh = false): Promise<PlannedMove[]> {
    const concepts = questionService.getAll();
    if (concepts.length === 0) return [];

    const signals = trajectoryAnalyzerService.aggregateSignals(forceRefresh);
    const existing = loadMoves();

    // Filter out concepts with recent duplicate moves.
    const candidates = concepts.filter((c) => !isRecentDuplicate(c.id, existing));
    if (candidates.length === 0) return existing;

    const ranked = rankConcepts(candidates, signals, 8);
    const newMoves = generateMoves(ranked, signals);

    // Merge: keep non-auto moves + non-expired auto moves + new moves.
    const cutoff = Date.now() - DAILY_REFRESH_INTERVAL_MS;
    const retained = existing.filter(
      (m) => !m.isAutoGenerated || m.createdAt > cutoff,
    );

    // Prevent total from exceeding 12 suggestions.
    const combined = [...newMoves, ...retained].slice(0, 12);
    saveMoves(combined);
    setLastRefreshTime(Date.now());

    // Invalidate trajectory cache so next aggregation picks up fresh data.
    trajectoryAnalyzerService.invalidateCache();

    eventBus.emit({ type: 'PLANNER_UPDATED', payload: { reason: 'chunk' } });
    return combined;
  },

  /** Remove a specific move (user dismissed it). */
  dismissMove(moveId: string): void {
    const moves = loadMoves();
    const updated = moves.filter((m) => m.id !== moveId);
    saveMoves(updated);
    eventBus.emit({ type: 'PLANNER_UPDATED', payload: { reason: 'chunk' } });
  },

  /** Dismiss all auto-generated moves (user skipped all). */
  dismissAllAutoMoves(): void {
    const moves = loadMoves();
    const updated = moves.filter((m) => !m.isAutoGenerated);
    saveMoves(updated);
    eventBus.emit({ type: 'PLANNER_UPDATED', payload: { reason: 'chunk' } });
  },

  /** Convert an auto-generated move into a PlannerChunk (user accepted it). */
  acceptMove(moveId: string): boolean {
    const moves = loadMoves();
    const move = moves.find((m) => m.id === moveId);
    if (!move) return false;

    // Map move type to chunk type
    const typeMap: Record<PlannedMove['moveType'], 'retrieve' | 'repair' | 'connect' | 'create'> = {
      review: 'retrieve',
      deepdive: 'create',
      connection: 'connect',
      podcast: 'repair',
    };

    plannerService.createChunk({
      type: typeMap[move.moveType],
      goal: move.title,
      description: move.reason,
      linkedConceptIds: [move.conceptId],
      status: 'suggested',
    });

    // Remove the move after accepting.
    saveMoves(moves.filter((m) => m.id !== moveId));
    // PLANNER_UPDATED already emitted by createChunk.
    return true;
  },

  /** Return timestamp of last refresh (0 if never refreshed). */
  getLastRefreshTime(): number {
    return getLastRefreshTime();
  },
};
