// ═══════════════════════════════════════════════════════════════════════════
// QUESTION & KNOWLEDGE DOMAIN
// ═══════════════════════════════════════════════════════════════════════════

export interface Question {
  id: string;
  timestamp: number;
  date: string;
  content: string;
  answer: string;
  summary: string;
  title?: string;          // short AI-derived title (4-7 words), used in listings
  storyHook?: string;      // intriguing one-liner to spark curiosity, shown in Info Flow
  parentId?: string;       // parent node ID for hierarchical graph organisation
  keywords: string[];
  relatedQuestionIds: string[];
  categoryIds: string[];
  reviewSchedule: ReviewSchedule;
  createdAt: number;
  aliases?: string[];
  sourcePrompts?: string[];
  sourceQuestionIds?: string[];
  rootLabel?: string;
  branchLabel?: string;
  clusterLabel?: string;
  nodeSummary?: string;
  placementReason?: string;
  lastReviewedAt?: number;
  pinned?: boolean;
  coCreationSignals?: Partial<Record<StructuralSignalType, number>> & { lastSignalAt?: number };
  embeddingVector?: number[];
  flagged?: boolean;  // true if detected as off-topic/meta-question; user can override
  prunedFromTrellis?: boolean; // true when user explicitly prunes this node from the trellis (D-15/D-17)
  isAnchorNode?: boolean;  // true for concept anchor nodes; undefined/false for Q&A leaf nodes
  qaCount?: number;        // number of Q&A nodes attached to this anchor (incremented on attachment)
  shortSummary?: string;   // <=80 words, used as anchor summary entry when Q&A attaches
  isClusterNode?: boolean; // true for cluster-level container nodes
  clusterNodeId?: string;  // on anchor and Q&A nodes — points to parent cluster entity ID
}

/** A milestone or trivia card injected into the Info Flow every ~5 items. */
export interface BlindboxItem {
  id: string;
  type: 'milestone' | 'trivia';
  emoji: string;
  headline: string;
  body: string;
}

export interface ReviewSchedule {
  nextReviewDate: string;
  reviewCount: number;
  easeFactor: number;
}

export interface Category {
  id: string;
  name: string;
  parentId?: string;
  color: string;
}

// ═══════════════════════════════════════════════════════════════════════════
// PLANNER DOMAIN
// ═══════════════════════════════════════════════════════════════════════════

/** Learning action types that a chunk can represent. */
export type ChunkType = 'review' | 'compare' | 'discover';

// ── Trajectory & Auto-Suggestions ──────────────────────────────────────────

/**
 * Aggregated learning trajectory signals used to score and rank auto-generated
 * Planner suggestions.
 */
export interface TrajectorySignal {
  /** 0-100, avg correctness on flashcards (derived from SM-2 easeFactor). */
  reviewPerformance: number;
  /** Questions asked in last 7 days. */
  questionFrequency: number;
  /** Milliseconds since the most-recently-reviewed question was reviewed. */
  timeSinceLastReview: number;
  /** Posts viewed in last 7 days. */
  feedEngagement: number;
  /** Percentage of knowledge graph nodes that have been reviewed at least once. */
  conceptCoverage: number;
  /** Question IDs with low review scores (easeFactor < 1.8). */
  weakAreas: string[];
}

/** Move types for auto-generated Planner suggestions. */
export type PlannedMoveType = 'review' | 'read' | 'compare' | 'podcast';

/**
 * An auto-generated Planner suggestion linking a knowledge concept to a
 * recommended learning action.
 */
export interface PlannedMove {
  id: string;
  /** Title / concept name for display. */
  title: string;
  /** Question/concept ID this move is about. */
  conceptId: string;
  /** Keywords from the concept (for dedup + display). */
  keywords: string[];
  moveType: PlannedMoveType;
  /** 0-100 relevance score (higher = more important). */
  relevanceScore: number;
  /** Human-readable reason shown to the user. */
  reason: string;
  /** Estimated time in milliseconds. */
  targetTime?: number;
  /** Linked resource for navigation. */
  linkedResource?: {
    type: 'post' | 'question' | 'review';
    id: string;
  };
  /** Whether this move was auto-generated (vs manually added). */
  isAutoGenerated: boolean;
  /** True if the concept was in the user's weak areas at generation time. */
  isWeakArea?: boolean;
  createdAt: number;
}

/** Soft lifecycle states for a planner chunk — no overdue/failure framing. */
export type ChunkStatus = 'suggested' | 'in_progress' | 'saved_for_later' | 'done';

/** A lightweight learning action card in the Planner. */
export interface PlannerChunk {
  id: string;
  type: ChunkType;
  /** Short learning goal or action label (e.g. "Compare X vs Y"). */
  goal: string;
  /** Optional longer description or context. */
  description?: string;
  /** IDs of related knowledge questions/nodes. */
  linkedConceptIds: string[];
  /** Which signal type created this chunk (confusion/curiosity/revisit/connection). */
  sourceSignal?: 'confusion' | 'curiosity' | 'revisit' | 'connection';
  /** Original check-in text that created this chunk. */
  sourceText?: string;
  /** Why this chunk was suggested (set by scoring service). */
  priorityReason?: string;
  /** Post ID to navigate to (set for compare chunks; for discover, generated on demand). */
  linkedPostId?: string;
  status: ChunkStatus;
  createdAt: number;
  updatedAt: number;
}

/** Structured signals extracted from a single Learning Check-In. */
export interface CheckInSignals {
  /** Concepts the user feels confident about. */
  confidence: string[];
  /** Concepts or areas that feel fuzzy or unresolved. */
  confusion: string[];
  /** Connections the user noticed or wants to explore. */
  connections: string[];
  /** Topics the user is curious about. */
  curiosity: string[];
  /** Specific items the user wants to revisit. */
  revisitIntent: string[];
}

/** A single Learning Check-In entry. */
export interface LearningCheckIn {
  id: string;
  /** Raw freeform text from the user (typed or transcribed). */
  content: string;
  /** Extracted structured signals. */
  signals: CheckInSignals;
  /** IDs of chunks suggested as a result. */
  generatedChunkIds: string[];
  createdAt: number;
}

/** Top-level planner data shape for persistence and state hooks. */
export interface PlannerData {
  chunks: PlannerChunk[];
  checkIns: LearningCheckIn[];
}

// ═══════════════════════════════════════════════════════════════════════════
// PODCAST DOMAIN
// ═══════════════════════════════════════════════════════════════════════════

export interface DailyPodcast {
  id: string;
  date: string;
  questionIds: string[];
  script: string;
  audioPath?: string;
  /** Base64 data URI of the synthesized audio — survives page reloads unlike blob URLs. */
  audioDataUri?: string;
  duration?: number;
  status: PodcastStatus;
  progress?: number;
  error?: string;
  createdAt: number;
  options?: PodcastOptions; // Phase 52 PODCAST-03
  optionsHash?: string; // Phase 52 PODCAST-03
}

export type PodcastStatus = 'pending' | 'generating' | 'ready' | 'failed';

/** Phase 52 PODCAST-02 (D-01): three bounded length presets (Phase 52 UAT GAP-1: operator dropped 'brief'). */
export type PodcastLength = 'standard' | 'deep' | 'extended';

/** Phase 52 PODCAST-02 (D-02): three bounded style presets. */
export type PodcastStyle = 'focused' | 'conversational' | 'review';

/** Phase 52 PODCAST-02/03: bounded options passed to generatePodcast + hashed for cache invalidation. */
export interface PodcastOptions {
  length: PodcastLength;
  style: PodcastStyle;
}

// ═══════════════════════════════════════════════════════════════════════════
// SETTINGS DOMAIN
// ═══════════════════════════════════════════════════════════════════════════

/** Which provider takes priority when generating images. */
export type ImageProviderPrimary = 'nanoBanana' | 'gemini' | 'auto';

export interface ImageGenerationSettings {
  nanoBananaApiKey: string;
  geminiApiKey: string;
  /** Gemini model name — e.g. 'gemini-3.1-flash-image-preview'. User-configurable so it never needs a code change. */
  geminiModel: string;
  maxCacheSizeMb: number;
  cacheTtlDays: number;
  /** Provider order preference. 'auto' tries both based on key availability. */
  primaryProvider: ImageProviderPrimary;
  /** Master toggle for image generation. When false, no API calls attempted. */
  enabled: boolean;
}

export interface AppSettings {
  llm: LLMConfig;
  /**
   * Phase 55.1 GAP-E (BUGFIX-08) — optional low-latency generation model.
   * When `enabled` and configured, the on-open one-shot generators (post body,
   * news essay, post-context Q&A) stream from THIS model with thinking/reasoning
   * DISABLED, so the body starts streaming immediately on tap-in (no multi-second
   * "thinking" stall). When unset/disabled, those generators fall back to `llm`
   * with NO behavior change. Mirrors LLMConfig so users can point it at a wholly
   * different provider/model/key (e.g. a fast local LM Studio model while `llm`
   * is a cloud reasoning model). Additive-optional — pre-feature stored settings
   * load the default (disabled) via deepMerge; no migration (CLAUDE.md
   * feedback_no_normalize_for_optional_fields). Ask Q&A / classification / planner /
   * podcast / flashcard are NOT routed through this — they keep `llm`.
   */
  fastModel?: FastModelConfig;
  tts: TTSConfig;
  embedding: EmbeddingConfig;
  embeddingDebug: EmbeddingDebugConfig;
  zerotier: ZeroTierConfig;
  podcast: PodcastSettings;
  review: ReviewSettings;
  preferences: AppPreferences;
  imageGeneration: ImageGenerationSettings;
  youtube: {
    apiKey: string;
  };
  webSearch: {
    tavilyApiKey: string;
  };
  feed: {
    postRetentionDays: number | null; // null = keep all
    dailyGenerationCapMultiplier: number;
    bonusPostCap: number;
  };
}

export interface EmbeddingConfig {
  provider: 'openai' | 'google' | 'local' | 'lmstudio';
  apiKey?: string;
  apiKeys?: Record<string, string>; // Phase 52 GAP-5 — per-provider key memory; undefined for pre-GAP-5 stored settings (read-site fallback, no migration per CLAUDE.md feedback_no_normalize_for_optional_fields)
  model: string;
  baseUrl?: string;
  dimensions?: number;
  isConfigured: boolean;
}

export interface EmbeddingDebugConfig {
  // Legacy field — retained for backwards-compat read side. Phase 55 D-05 stops
  // rendering its slider (it never mapped to any real threshold). Do NOT reconnect
  // this to anchor dedup.
  similarityThreshold: number;
  showScores: boolean;
  // Phase 55 D-05: per-threshold live tuning knobs. Optional + additive — pre-feature
  // stored settings load with these undefined and every read path falls back to the
  // hardcoded service constant (no normalize framework per CLAUDE.md
  // feedback_no_normalize_for_optional_fields). debugEnabled is the master gate:
  // false/undefined = production mode (constants used unconditionally).
  debugEnabled?: boolean;        // master gate; false/undefined = production mode
  offTopicThreshold?: number;    // RETIRED by RAW-ARGMAX (Phase 55): the filter's off/on split is now relative, no absolute off-topic threshold. Field kept for stored-settings backward-compat; not read.
  maliciousThreshold?: number;   // RAW-ARGMAX malicious-FLOOR debug override; clamped to [0.35, 0.70] by resolveMaliciousFloor (was the absolute malicious threshold pre-Phase-55)
  anchorDedupThreshold?: number; // default 0.82 when undefined; clamped to [0.78, 0.85] by service (separate anchor-dedup classifier — unaffected by RAW-ARGMAX)
}

export interface LLMConfig {
  provider: 'openai' | 'claude' | 'gemini' | 'local' | 'lmstudio';
  apiKey?: string;
  apiKeys?: Record<string, string>; // Phase 52 GAP-5 — per-provider key memory; undefined for pre-GAP-5 stored settings (read-site fallback, no migration per CLAUDE.md feedback_no_normalize_for_optional_fields)
  baseUrl?: string;
  model: string;
  isConfigured: boolean;
}

/**
 * Phase 55.1 GAP-E — low-latency generation model config. Mirrors LLMConfig (so the
 * Settings UI + provider plumbing reuse existing patterns) plus an `enabled` master gate.
 * `resolveGenerationConfig` returns this config (with thinking disabled) ONLY when
 * `enabled === true` AND `isConfigured === true`; otherwise it falls back to the main
 * `llm` config with thinking left on (byte-identical request to today).
 */
export interface FastModelConfig extends LLMConfig {
  enabled: boolean;
}

export interface TTSConfig {
  provider: 'openai' | 'gptsovits';
  apiKey?: string;
  baseUrl?: string;
  voice: string;
  speed: number;
  isConfigured: boolean;
  model?: string; // Phase 52 PODCAST-05 (D-07): default 'tts-1', opt-in 'tts-1-hd'
}

export interface ZeroTierConfig {
  networkId?: string;
  isConnected: boolean;
  virtualIp?: string;
}

export interface PodcastSettings {
  sleepTime: string;
  advanceMinutes: number;
  autoGenerate: boolean;
  defaultLength?: PodcastLength; // Phase 52 — undefined falls back at read site (D-14)
  defaultStyle?: PodcastStyle; // Phase 52 — undefined falls back at read site (D-14)
}

export interface ReviewSettings {
  dailyLimit: number;
  notificationsEnabled: boolean;
  reminderTime: string;
}

/** Supported i18n locales. Canonical source in `app/src/locales/index.ts`; inlined here to avoid cross-module dependency. */
export type SupportedLocale = 'en' | 'zh' | 'es' | 'ja';

export interface AppPreferences {
  theme: 'light' | 'dark' | 'system';
  /** Canonical display locale (D-20). Populated from legacy `language` field on first load when missing. */
  locale: SupportedLocale;
  /** @deprecated Use `locale` instead. Kept for one-time migration only. */
  language?: string;
  onboardingCompleted: boolean;
  /** Explicit user consent to transmit questions to the configured AI provider. Required by App Store / Play Store AI policies. */
  aiConsentGiven?: boolean;
  /** Monthly cap on user Q&A requests. 0 = unlimited (default). */
  askMonthlyLimit?: number;
}

// ═══════════════════════════════════════════════════════════════════════════
// CHAT SESSION DOMAIN
// ═══════════════════════════════════════════════════════════════════════════

export interface SessionMessage {
  id: string;
  type: 'user' | 'ai';
  content: string;
  relatedKnowledge?: string[];
  questionId?: string;
  // isStreaming is transient UI state only — never persisted
  /**
   * Discriminator for special-render AI messages. Phase 47 D-01 / D-02:
   *   - undefined / 'normal' → existing markdown body render path.
   *   - 'malicious-block'    → ChatMessage renders the inline rejection
   *                            surface (NO override button, neutral copy
   *                            from i18n key chatMessage.maliciousBlocked.body).
   * useQuestions.askStreaming sets 'malicious-block' when filterResult.label
   * === 'malicious' (pre-LLM gate per D-18). Zero LLM tokens are spent in
   * this branch, no Question is persisted.
   */
  kind?: 'normal' | 'malicious-block';
}

export interface ChatSession {
  id: string;
  title: string;       // first user message, truncated to 60 chars
  createdAt: number;
  updatedAt: number;
  messages: SessionMessage[];
  processed: boolean;  // true once flashcard post-processing has run
  origin?: SessionOrigin;
}

// ═══════════════════════════════════════════════════════════════════════════
// FLASHCARD DOMAIN
// ═══════════════════════════════════════════════════════════════════════════

export interface FlashCard {
  id: string;
  sessionId: string;        // which ChatSession produced this card
  front: string;            // concise question / concept (≤120 chars)
  back: string;             // concise answer (≤200 chars)
  createdAt: number;
  pinned?: boolean;         // if true, appears in review queue every day
  reviewSchedule: ReviewSchedule;
  nodeId?: string;
  nodeTitle?: string;
  rootLabel?: string;
  branchLabel?: string;
  clusterLabel?: string;
  placementReason?: string;
  sourceType?: 'canonical' | 'legacy';
}

export type StructuralSignalType = 'sameIdea' | 'connect' | 'refine';

export interface KnowledgeNode {
  id: string;
  title: string;
  content: string;
  answer: string;
  summary: string;
  storyHook?: string;
  keywords: string[];
  relatedQuestionIds: string[];
  parentId?: string;
  aliases: string[];
  sourcePrompts: string[];
  sourceQuestionIds: string[];
  rootLabel: string;
  branchLabel: string;
  clusterLabel: string;
  nodeSummary: string;
  placementReason: string;
  reviewSchedule: ReviewSchedule;
  createdAt: number;
  date: string;
  timestamp: number;
  lastReviewedAt?: number;
  pinned?: boolean;
  coCreationSignals?: Partial<Record<StructuralSignalType, number>> & { lastSignalAt?: number };
}

export interface HierarchySummary {
  id: string;
  label: string;
  summary: string;
  representativeKeywords: string[];
  representativeNodeIds: string[];
  nodeCount: number;
}

export interface CandidateContextPack {
  roots: HierarchySummary[];
  branches: HierarchySummary[];
  clusters: HierarchySummary[];
  candidates: KnowledgeNode[];
}

export interface IngestionDecision {
  outcome: 'merge' | 'refine' | 'new';
  targetNodeId?: string;
}

export interface ClassificationResult {
  briefAnswer: string;
  keyword: string;
  rootLabel: string;
  branchLabel: string;
  clusterLabel: string;
  anchorName: string;
  anchorId?: string;
}

export interface ReorganizationResult {
  hierarchy: Array<{
    rootLabel: string;
    branches: Array<{
      branchLabel: string;
      clusters: Array<{
        clusterLabel: string;
        anchors: Array<{
          anchorName: string;
          keyword: string;
          qaIds: string[];
        }>;
      }>;
    }>;
  }>;
}

export interface ReviewMapLeaf {
  nodeId: string;
  label: string;
  state: 'hidden' | 'revealed' | 'active';
}

export interface ReviewMapCluster {
  id: string;
  label: string;
  leaves: ReviewMapLeaf[];
}

export interface ReviewMapBranch {
  id: string;
  label: string;
  clusters: ReviewMapCluster[];
}

export interface ReviewMapRoot {
  id: string;
  label: string;
  branches: ReviewMapBranch[];
}

export interface DailyReviewMap {
  roots: ReviewMapRoot[];
  totalDue: number;
  revealedCount: number;
}

export type PostNarrativeMode =
  | 'example-first'
  | 'historical-story'
  | 'contrast'
  | 'analogy'
  | 'false-intuition'
  | 'mnemonic'
  | 'mechanism-breakdown'
  | 'starter';

/** Visual presentation style assigned to each feed post by the weighted mix algorithm. */
export type PresentationStyle = 'image' | 'text-art' | 'image-less' | 'video' | 'news' | 'suggestion';

export interface FeedTeaser {
  hook: string;
  preview: string;
}

export interface PostSnapshot {
  id: string;
  date: string;
  title: string;
  teaser: FeedTeaser;
  bodyMarkdown: string;
  /** Phase 41 D-03 — optional 350-600w deep variant. Generated on demand,
   *  lives alongside the standard bodyMarkdown teaser. Back-compat additive:
   *  old cached posts without this field remain valid. */
  bodyMarkdownDeep?: string;
  whyCare: string;
  takeaway: string;
  quickAskPrompts: string[];
  narrativeMode: PostNarrativeMode;
  contextLabel: string;
  sourceType: 'recent' | 'related' | 'resurfaced' | 'starter' | 'mixed' | 'connection' | 'video' | 'text-art' | 'news' | 'suggestion';
  sourceQuestionIds: string[];
  sourceQuestionTitles: string[];
  keywords: string[];
}

export interface WebSearchResult {
  title: string;
  url: string;
  content: string;  // clean text snippet from Tavily
  score: number;    // relevance 0-1
}

export interface WebSearchResponse {
  results: WebSearchResult[];
  images?: string[];
  query: string;
  responseTime: number;
}

export interface SourceCitation {
  index: number;
  title: string;
  url: string;
  snippet?: string;
}

export interface VideoMetadata {
  videoId: string;
  channelTitle: string;
  thumbnailUrl: string;
  transcript?: string;
  summary?: string;
  duration?: string;
}

export interface DailyPost extends PostSnapshot {
  generatedAt: number;
  origin: 'ai';
  videoMeta?: VideoMetadata;
  /** ASCII/Unicode text-art content for text-art presentation style. */
  textArtContent?: string;
  /** Visual presentation style assigned by the weighted mix algorithm. */
  presentationStyle?: PresentationStyle;
  /** News post metadata with source citations and fetch timestamp. */
  newsMeta?: {
    sources: SourceCitation[];
    fetchedAt: number;
    imageUrl?: string;
  };
  /** Suggestion post metadata with topic suggestions for further exploration. */
  suggestionMeta?: SuggestionMeta;
}

/** Metadata for suggestion-type posts that propose new topics to explore. */
export interface SuggestionMeta {
  topics: string[]; // exactly 3 topic strings
}

export interface PostOriginContext {
  post: PostSnapshot;
  sourceQuestions: Array<{
    id: string;
    title: string;
    content: string;
    summary: string;
  }>;
}

export interface SessionOrigin {
  type: 'post';
  postId: string;
  postTitle: string;
  context: PostOriginContext;
}

/**
 * User-defined post collection (YouTube-playlist analogy). Phase 50 D-03.
 * Persisted under localStorage key `trellis_collections_v1` by
 * `collectionService` (50-03). Storage is ID-only — `DailyPost` snapshots are
 * resolved at read time via `postHistoryService.getPosts()`. A post can
 * belong to multiple collections; collection membership pins a post against
 * the 7-day rolling history purge via `engagementService.getPinnedIds()`
 * (D-09).
 */
export interface Collection {
  id: string;
  name: string;
  postIds: string[];
  createdAt: number;
  updatedAt: number;
}

// ═══════════════════════════════════════════════════════════════════════════
// IMAGE GENERATION DOMAIN
// ═══════════════════════════════════════════════════════════════════════════

export type ImageStyle = 'infograph' | 'illustration' | 'photo';
export type ImageProvider = 'nanoBanana' | 'gemini' | 'mock';

export interface GeneratedImage {
  id: string;
  postId: string;
  prompt: string;
  style: ImageStyle;
  imageUrl?: string;       // Remote URL (if from provider)
  imageBase64?: string;    // Local cache (base64 data URI)
  provider: ImageProvider;
  generatedAt: number;
  cachedAt?: number;
  error?: string;
}

export interface ImageCacheMetadata {
  postId: string;
  style: ImageStyle;
  provider: ImageProvider;
  generatedAt: number;
  cachedAt: number;
  expiresAt: number;
  sizeBytes: number;
}

export interface CacheStats {
  totalSizeBytes: number;
  itemCount: number;
  oldestItemAt: number | null;
  newestItemAt: number | null;
}

export interface ImageGenerationConfig {
  nanoBananaApiKey?: string;
  geminiApiKey?: string;
  maxCacheSizeBytes: number;
  cacheTtlMs: number;
  requestTimeoutMs: number;
  maxRetries: number;
}

// ═══════════════════════════════════════════════════════════════════════════
// SHARED RESPONSE TYPE
// ═══════════════════════════════════════════════════════════════════════════

export interface ServiceResult<T> {
  success: boolean;
  data?: T;
  error?: ServiceError;
}

export interface ServiceError {
  code: ErrorCode;
  message: string;
  retryable: boolean;
}

export type ErrorCode =
  | 'NETWORK_ERROR'
  | 'API_KEY_INVALID'
  | 'API_KEY_NOT_CONFIGURED'
  | 'API_QUOTA_EXCEEDED'
  | 'API_RATE_LIMITED'
  | 'DATABASE_ERROR'
  | 'INVALID_REQUEST'
  | 'NOT_FOUND'
  | 'RETRIES_EXHAUSTED'
  | 'VALIDATION_ERROR'
  | 'NOT_CONFIGURED'
  | 'UNKNOWN_ERROR'
  | 'NO_BACKUP'
  | 'REVERT_ERROR'
  | 'IN_PROGRESS'
  | 'TOO_FEW'
  | 'PARSE_ERROR'
  | 'SEARCH_FAILED'
  | 'LLM_ERROR'
  | 'COVERAGE_ERROR'
  // Phase 47 — pre-LLM filter gate (D-01). Returned from question.service.ask
  // when the filter classifies the input as malicious; no override path.
  | 'BLOCKED_MALICIOUS'
  // Phase 47 — pre-LLM filter gate (D-19). Returned from question.service.ask
  // when the abort signal fires during the pre-gate (LOCALE_CHANGED, etc.).
  | 'ABORTED'
  // Phase 48 — graphCommandService.delete returns this when the underlying
  // questionService.delete reports { success: false } (e.g. SQLite write
  // failure). Plan 48-02 Task 3 uses this for the Blocker #2 abort-before-
  // journal path. Retryable: the operator can retry the command.
  | 'STORAGE_ERROR'
  // Phase 48 — Plan 48-02 ships graphCommandService with method-stubs for
  // merge/detach/prune (filled in Plan 48-03) and undo (filled in Plan
  // 48-04). Callers see NOT_IMPLEMENTED until the implementing plans land.
  | 'NOT_IMPLEMENTED';

export interface AskResult {
  question: Question;
  relatedQuestions: Question[];
  newConnections: number;
}

// ═══════════════════════════════════════════════════════════════════════════
// EVENT SYSTEM
// ═══════════════════════════════════════════════════════════════════════════

export type AppEvent =
  | { type: 'QUESTION_ASKED'; payload: Question }
  | { type: 'QUESTION_DELETED'; payload: { id: string } }
  | { type: 'CATEGORY_CREATED'; payload: Category }
  | { type: 'REVIEW_SUBMITTED'; payload: { questionId: string; rating: number } }
  | { type: 'REVIEW_DUE_COUNT_CHANGED'; payload: { count: number } }
  | { type: 'PLANNER_UPDATED'; payload: { reason: 'chunk' } }
  | { type: 'PODCAST_GENERATION_STARTED'; payload: { podcastId: string; date: string } }
  | { type: 'PODCAST_GENERATION_PROGRESS'; payload: { podcastId: string; progress: number } }
  | { type: 'PODCAST_GENERATION_COMPLETED'; payload: DailyPodcast }
  | { type: 'PODCAST_GENERATION_FAILED'; payload: { podcastId: string; error: string } }
  | { type: 'PODCAST_CONCEPT_ADDED'; payload: { podcastId: string; questionId: string } }
  | { type: 'LLM_CONFIG_CHANGED'; payload: LLMConfig }
  | { type: 'TTS_CONFIG_CHANGED'; payload: TTSConfig }
  | { type: 'LOCALE_CHANGED'; payload: { locale: SupportedLocale } }
  | { type: 'ZEROTIER_STATUS_CHANGED'; payload: ZeroTierConfig }
  | { type: 'NETWORK_STATUS_CHANGED'; payload: { isOnline: boolean } }
  | { type: 'POST_DELETED'; payload: { id: string } }
  // Emitted once per refill cycle that actually RUNS (the `needsRefill()`
  // early-return does not emit). `added` is the realized queue growth; `error`
  // is set only when the cycle threw. HomeScreen needs this because
  // getDailyPosts() returns [] on a cold start BY DESIGN while refillQueue
  // works in the background — without a completion signal an empty feed is
  // indistinguishable from a broken API key.
  | { type: 'FEED_REFILL_COMPLETED'; payload: { added: number; error?: string } }
  | { type: 'SESSION_CREATED'; payload: ChatSession }
  | { type: 'SESSION_UPDATED'; payload: { id: string } }
  | { type: 'FLASHCARDS_CREATED'; payload: { sessionId: string; count: number } }
  | { type: 'AUTO_GEN_UPDATED'; payload: { moves: unknown[]; count: number } }
  | { type: 'REORG_STARTED' }
  | { type: 'REORG_COMPLETED'; payload: { anchorCount: number; clusterCount: number } }
  | { type: 'REORG_FAILED'; payload: { error: string } }
  | { type: 'REVIEW_COMPLETED'; payload: { questionId: string; anchorId?: string } }
  | { type: 'ANCHOR_DELETED'; payload: { anchorId: string } }
  | { type: 'HARVEST_COMPLETED'; payload: { count: number } }
  | { type: 'CONCEPT_EXPLORED'; payload: { anchorId: string } }
  | { type: 'ANCHOR_DISMISSED'; payload: { anchorId: string } }
  | { type: 'ENGAGEMENT_CHANGED'; payload: { kind: 'save' | 'unsave' | 'like' | 'unlike' | 'undismiss' | 'save-podcast' | 'unsave-podcast'; id: string } }
  // Phase 50 D-03 + Claude's Discretion in 50-CONTEXT.md. One signal per
  // semantic event (CLAUDE.md §"Event bus — unified GRAPH_UPDATED"): a single
  // COLLECTIONS_CHANGED event with a discriminating `kind` payload covers
  // create/rename/delete plus add-post / remove-post membership mutations.
  // Subscribers (SavedScreen Collections sub-tab, collection drill-in view,
  // CollectionPickerSheet) re-read collectionService on any kind.
  | {
      type: 'COLLECTIONS_CHANGED';
      payload: {
        kind: 'create' | 'rename' | 'delete' | 'add-post' | 'remove-post';
        collectionId: string;
      };
    }
  // Unified graph-mutation signal. Fires after any classification commit, anchor
  // creation, prune, replant, or reorg step. Subscribers don't need to discriminate
  // why the graph changed — just re-read store. Replaces the former
  // CLASSIFICATION_COMPLETED event (semantic duplicate of this one; payload was
  // never read by any subscriber).
  //
  // Phase 48 (D-17, R5): payload is OPTIONAL — emit sites that don't need to
  // discriminate may continue passing `{ type: 'GRAPH_UPDATED' }`. New emit
  // sites (graphCommandService rename/move/merge/detach/prune/delete/undo) may
  // pass payload.kind so future Phase 49 toast logic can distinguish an undo
  // from the original command. The `'undo'` literal lives ONLY in this
  // event-bus payload union, NEVER in GraphEditLogEntry.cmd (R Summary
  // point 6 — undo writes the inverse verb with swapped before/after, so the
  // journal records what literally happened, not the semantic intent).
  | {
      type: 'GRAPH_UPDATED';
      payload?: {
        kind?: 'rename' | 'move' | 'merge' | 'detach' | 'prune' | 'delete'
             | 'undo' | 'classification' | 'replant' | 'unprune';
        anchorId?: string;
        affectedIds?: string[];
      };
    };

// ═══════════════════════════════════════════════════════════════════════════
// GRAPH EDIT JOURNAL (Phase 48 — D-04)
// ═══════════════════════════════════════════════════════════════════════════

// Append-only edit log written by graphCommandService and consumed by
// (a) graphCommandService.undo() — pops newest and applies inverse, and
// (b) reorganizeMindmap()'s system-prompt builder — projects entries as
// "Manual corrections to preserve:" constraint lines (D-01, D-20).
//
// cmd is the SIX real verbs; undo writes the inverse verb with swapped
// before/after per R Summary point 6. Do NOT add 'undo' to this union —
// the journal records what literally happened (a rename, a move, etc.),
// not semantic intent. 'undo' lives only in the GRAPH_UPDATED event-bus
// payload's `kind` union above so Phase 49 can show "Undid: rename" toasts.
//
// `before` shape per R2 spec: compact field diff for rename/move/prune/detach;
// FULL Question record for delete/merge-loser so undo can resurrect.
// `before` is validated by isValidPreImage() before being applied (T-48-01
// tamper-resistance — guards against XSS or malicious browser extensions
// rewriting trellis_graph_edit_log to inject arbitrary resurrected content).
export interface GraphEditLogEntry {
  id: string;                  // `${Date.now()}-${Math.random().toString(36).slice(2, 7)}`
  ts: number;                  // Date.now()
  cmd: 'rename' | 'move' | 'merge' | 'detach' | 'prune' | 'delete';
  targetIds: string[];
  before: Record<string, unknown>;
  after: Record<string, unknown>;
}
