// ═══════════════════════════════════════════════════════════════════════════
// QUESTION & KNOWLEDGE DOMAIN
// ═══════════════════════════════════════════════════════════════════════════

export interface Question {
  id: string;
  timestamp: number;
  date: string;
  content: string;
  answer: string;
  summary: string;
  title?: string;          // short AI-derived title (4-7 words), used in listings
  storyHook?: string;      // intriguing one-liner to spark curiosity, shown in Info Flow
  parentId?: string;       // parent node ID for hierarchical graph organisation
  keywords: string[];
  relatedQuestionIds: string[];
  categoryIds: string[];
  reviewSchedule: ReviewSchedule;
  createdAt: number;
  aliases?: string[];
  sourcePrompts?: string[];
  sourceQuestionIds?: string[];
  rootLabel?: string;
  branchLabel?: string;
  clusterLabel?: string;
  nodeSummary?: string;
  placementReason?: string;
  lastReviewedAt?: number;
  pinned?: boolean;
  coCreationSignals?: Partial<Record<StructuralSignalType, number>> & { lastSignalAt?: number };
  embeddingVector?: number[];
  flagged?: boolean;  // true if detected as off-topic/meta-question; user can override
}

/** A milestone or trivia card injected into the Info Flow every ~5 items. */
export interface BlindboxItem {
  id: string;
  type: 'milestone' | 'trivia';
  emoji: string;
  headline: string;
  body: string;
}

export interface ReviewSchedule {
  nextReviewDate: string;
  reviewCount: number;
  easeFactor: number;
}

export interface Category {
  id: string;
  name: string;
  parentId?: string;
  color: string;
}

// ═══════════════════════════════════════════════════════════════════════════
// PLANNER DOMAIN
// ═══════════════════════════════════════════════════════════════════════════

/** Learning action types that a chunk can represent. */
export type ChunkType = 'retrieve' | 'repair' | 'connect' | 'create';

// ── Trajectory & Auto-Suggestions ──────────────────────────────────────────

/**
 * Aggregated learning trajectory signals used to score and rank auto-generated
 * Planner suggestions.
 */
export interface TrajectorySignal {
  /** 0-100, avg correctness on flashcards (derived from SM-2 easeFactor). */
  reviewPerformance: number;
  /** Questions asked in last 7 days. */
  questionFrequency: number;
  /** Milliseconds since the most-recently-reviewed question was reviewed. */
  timeSinceLastReview: number;
  /** Posts viewed in last 7 days. */
  feedEngagement: number;
  /** Percentage of knowledge graph nodes that have been reviewed at least once. */
  conceptCoverage: number;
  /** Question IDs with low review scores (easeFactor < 1.8). */
  weakAreas: string[];
}

/** Move types for auto-generated Planner suggestions. */
export type PlannedMoveType = 'review' | 'deepdive' | 'connection' | 'podcast';

/**
 * An auto-generated Planner suggestion linking a knowledge concept to a
 * recommended learning action.
 */
export interface PlannedMove {
  id: string;
  /** Title / concept name for display. */
  title: string;
  /** Question/concept ID this move is about. */
  conceptId: string;
  /** Keywords from the concept (for dedup + display). */
  keywords: string[];
  moveType: PlannedMoveType;
  /** 0-100 relevance score (higher = more important). */
  relevanceScore: number;
  /** Human-readable reason shown to the user. */
  reason: string;
  /** Estimated time in milliseconds. */
  targetTime?: number;
  /** Linked resource for navigation. */
  linkedResource?: {
    type: 'post' | 'question' | 'review';
    id: string;
  };
  /** Whether this move was auto-generated (vs manually added). */
  isAutoGenerated: boolean;
  createdAt: number;
}

/** Soft lifecycle states for a planner chunk — no overdue/failure framing. */
export type ChunkStatus = 'suggested' | 'in_progress' | 'saved_for_later' | 'done';

/** A lightweight learning action card in the Planner. */
export interface PlannerChunk {
  id: string;
  type: ChunkType;
  /** Short learning goal or action label (e.g. "Compare X vs Y"). */
  goal: string;
  /** Optional longer description or context. */
  description?: string;
  /** IDs of related knowledge questions/nodes. */
  linkedConceptIds: string[];
  /** Thread this chunk was spawned from, if any. */
  threadId?: string;
  status: ChunkStatus;
  createdAt: number;
  updatedAt: number;
}

/** A persistent learning topic or unresolved area the user may return to. */
export interface PlannerThread {
  id: string;
  /** Short topic label (e.g. "TCP vs UDP differences"). */
  title: string;
  /** Optional longer description of the thread. */
  description?: string;
  /** Keywords for matching check-in signals to existing threads. */
  keywords: string[];
  /** IDs of related knowledge questions/nodes. */
  linkedConceptIds: string[];
  /** Whether the user explicitly saved this thread. */
  saved: boolean;
  /** Last time this thread was created or updated by a check-in. */
  lastActivityAt: number;
  createdAt: number;
}

/** Structured signals extracted from a single Learning Check-In. */
export interface CheckInSignals {
  /** Concepts the user feels confident about. */
  confidence: string[];
  /** Concepts or areas that feel fuzzy or unresolved. */
  confusion: string[];
  /** Connections the user noticed or wants to explore. */
  connections: string[];
  /** Topics the user is curious about. */
  curiosity: string[];
  /** Specific items the user wants to revisit. */
  revisitIntent: string[];
}

/** A single Learning Check-In entry. */
export interface LearningCheckIn {
  id: string;
  /** Raw freeform text from the user (typed or transcribed). */
  content: string;
  /** Extracted structured signals. */
  signals: CheckInSignals;
  /** IDs of threads created or updated as a result. */
  affectedThreadIds: string[];
  /** IDs of chunks suggested as a result. */
  generatedChunkIds: string[];
  createdAt: number;
}

/** Top-level planner data shape for persistence and state hooks. */
export interface PlannerData {
  chunks: PlannerChunk[];
  threads: PlannerThread[];
  checkIns: LearningCheckIn[];
}

// ═══════════════════════════════════════════════════════════════════════════
// PODCAST DOMAIN
// ═══════════════════════════════════════════════════════════════════════════

export interface DailyPodcast {
  id: string;
  date: string;
  questionIds: string[];
  script: string;
  audioPath?: string;
  /** Base64 data URI of the synthesized audio — survives page reloads unlike blob URLs. */
  audioDataUri?: string;
  duration?: number;
  status: PodcastStatus;
  progress?: number;
  error?: string;
  createdAt: number;
}

export type PodcastStatus = 'pending' | 'generating' | 'ready' | 'failed';

// ═══════════════════════════════════════════════════════════════════════════
// SETTINGS DOMAIN
// ═══════════════════════════════════════════════════════════════════════════

/** Which provider takes priority when generating images. */
export type ImageProviderPrimary = 'nanoBanana' | 'gemini' | 'auto';

export interface ImageGenerationSettings {
  nanoBananaApiKey: string;
  geminiApiKey: string;
  /** Gemini model name — e.g. 'gemini-3.1-flash-image-preview'. User-configurable so it never needs a code change. */
  geminiModel: string;
  maxCacheSizeMb: number;
  cacheTtlDays: number;
  /** Provider order preference. 'auto' tries both based on key availability. */
  primaryProvider: ImageProviderPrimary;
}

export interface AppSettings {
  llm: LLMConfig;
  tts: TTSConfig;
  embedding: EmbeddingConfig;
  embeddingDebug: EmbeddingDebugConfig;
  zerotier: ZeroTierConfig;
  podcast: PodcastSettings;
  review: ReviewSettings;
  preferences: AppPreferences;
  imageGeneration: ImageGenerationSettings;
}

export interface EmbeddingConfig {
  provider: 'openai' | 'google' | 'local';
  apiKey?: string;
  model: string;
  baseUrl?: string;
  dimensions?: number;
  isConfigured: boolean;
}

export interface EmbeddingDebugConfig {
  similarityThreshold: number;
  showScores: boolean;
}

export interface LLMConfig {
  provider: 'openai' | 'claude' | 'gemini' | 'local' | 'lmstudio';
  apiKey?: string;
  baseUrl?: string;
  model: string;
  isConfigured: boolean;
}

export interface TTSConfig {
  provider: 'openai' | 'gptsovits';
  apiKey?: string;
  baseUrl?: string;
  voice: string;
  speed: number;
  isConfigured: boolean;
}

export interface ZeroTierConfig {
  networkId?: string;
  isConnected: boolean;
  virtualIp?: string;
}

export interface PodcastSettings {
  sleepTime: string;
  advanceMinutes: number;
  autoGenerate: boolean;
}

export interface ReviewSettings {
  dailyLimit: number;
  notificationsEnabled: boolean;
  reminderTime: string;
}

export interface AppPreferences {
  theme: 'light' | 'dark' | 'system';
  language: string;
  onboardingCompleted: boolean;
  /** Explicit user consent to transmit questions to the configured AI provider. Required by App Store / Play Store AI policies. */
  aiConsentGiven?: boolean;
}

// ═══════════════════════════════════════════════════════════════════════════
// CHAT SESSION DOMAIN
// ═══════════════════════════════════════════════════════════════════════════

export interface SessionMessage {
  id: string;
  type: 'user' | 'ai';
  content: string;
  relatedKnowledge?: string[];
  questionId?: string;
  // isStreaming is transient UI state only — never persisted
}

export interface ChatSession {
  id: string;
  title: string;       // first user message, truncated to 60 chars
  createdAt: number;
  updatedAt: number;
  messages: SessionMessage[];
  processed: boolean;  // true once flashcard post-processing has run
  origin?: SessionOrigin;
}

// ═══════════════════════════════════════════════════════════════════════════
// FLASHCARD DOMAIN
// ═══════════════════════════════════════════════════════════════════════════

export interface FlashCard {
  id: string;
  sessionId: string;        // which ChatSession produced this card
  front: string;            // concise question / concept (≤120 chars)
  back: string;             // concise answer (≤200 chars)
  createdAt: number;
  pinned?: boolean;         // if true, appears in review queue every day
  reviewSchedule: ReviewSchedule;
  nodeId?: string;
  nodeTitle?: string;
  rootLabel?: string;
  branchLabel?: string;
  clusterLabel?: string;
  placementReason?: string;
  sourceType?: 'canonical' | 'legacy';
}

export type StructuralSignalType = 'sameIdea' | 'connect' | 'refine';

export interface KnowledgeNode {
  id: string;
  title: string;
  content: string;
  answer: string;
  summary: string;
  storyHook?: string;
  keywords: string[];
  relatedQuestionIds: string[];
  parentId?: string;
  aliases: string[];
  sourcePrompts: string[];
  sourceQuestionIds: string[];
  rootLabel: string;
  branchLabel: string;
  clusterLabel: string;
  nodeSummary: string;
  placementReason: string;
  reviewSchedule: ReviewSchedule;
  createdAt: number;
  date: string;
  timestamp: number;
  lastReviewedAt?: number;
  pinned?: boolean;
  coCreationSignals?: Partial<Record<StructuralSignalType, number>> & { lastSignalAt?: number };
}

export interface HierarchySummary {
  id: string;
  label: string;
  summary: string;
  representativeKeywords: string[];
  representativeNodeIds: string[];
  nodeCount: number;
}

export interface CandidateContextPack {
  roots: HierarchySummary[];
  branches: HierarchySummary[];
  clusters: HierarchySummary[];
  candidates: KnowledgeNode[];
}

export interface IngestionDecision {
  outcome: 'merge' | 'refine' | 'new';
  targetNodeId?: string;
  rootLabel?: string;
  branchLabel?: string;
  clusterLabel?: string;
  placementReason?: string;
}

export interface ReviewMapLeaf {
  nodeId: string;
  label: string;
  state: 'hidden' | 'revealed' | 'active';
}

export interface ReviewMapCluster {
  id: string;
  label: string;
  leaves: ReviewMapLeaf[];
}

export interface ReviewMapBranch {
  id: string;
  label: string;
  clusters: ReviewMapCluster[];
}

export interface ReviewMapRoot {
  id: string;
  label: string;
  branches: ReviewMapBranch[];
}

export interface DailyReviewMap {
  roots: ReviewMapRoot[];
  totalDue: number;
  revealedCount: number;
}

export type PostNarrativeMode =
  | 'example-first'
  | 'historical-story'
  | 'contrast'
  | 'analogy'
  | 'false-intuition'
  | 'mnemonic'
  | 'mechanism-breakdown'
  | 'starter';

export interface FeedTeaser {
  hook: string;
  preview: string;
}

export interface PostSnapshot {
  id: string;
  date: string;
  title: string;
  teaser: FeedTeaser;
  bodyMarkdown: string;
  whyCare: string;
  takeaway: string;
  quickAskPrompts: string[];
  narrativeMode: PostNarrativeMode;
  contextLabel: string;
  sourceType: 'recent' | 'related' | 'resurfaced' | 'starter' | 'mixed' | 'connection';
  sourceQuestionIds: string[];
  sourceQuestionTitles: string[];
  keywords: string[];
}

export interface DailyPost extends PostSnapshot {
  generatedAt: number;
  origin: 'ai' | 'fallback';
}

export interface PostOriginContext {
  post: PostSnapshot;
  sourceQuestions: Array<{
    id: string;
    title: string;
    content: string;
    summary: string;
  }>;
}

export interface SessionOrigin {
  type: 'post';
  postId: string;
  postTitle: string;
  context: PostOriginContext;
}

// ═══════════════════════════════════════════════════════════════════════════
// IMAGE GENERATION DOMAIN
// ═══════════════════════════════════════════════════════════════════════════

export type ImageStyle = 'infograph' | 'illustration' | 'photo';
export type ImageProvider = 'nanoBanana' | 'gemini' | 'mock';

export interface GeneratedImage {
  id: string;
  postId: string;
  prompt: string;
  style: ImageStyle;
  imageUrl?: string;       // Remote URL (if from provider)
  imageBase64?: string;    // Local cache (base64 data URI)
  provider: ImageProvider;
  generatedAt: number;
  cachedAt?: number;
  error?: string;
}

export interface ImageCacheMetadata {
  postId: string;
  style: ImageStyle;
  provider: ImageProvider;
  generatedAt: number;
  cachedAt: number;
  expiresAt: number;
  sizeBytes: number;
}

export interface CacheStats {
  totalSizeBytes: number;
  itemCount: number;
  oldestItemAt: number | null;
  newestItemAt: number | null;
}

export interface ImageGenerationConfig {
  nanoBananaApiKey?: string;
  geminiApiKey?: string;
  maxCacheSizeBytes: number;
  cacheTtlMs: number;
  requestTimeoutMs: number;
  maxRetries: number;
}

// ═══════════════════════════════════════════════════════════════════════════
// SHARED RESPONSE TYPE
// ═══════════════════════════════════════════════════════════════════════════

export interface ServiceResult<T> {
  success: boolean;
  data?: T;
  error?: ServiceError;
}

export interface ServiceError {
  code: ErrorCode;
  message: string;
  retryable: boolean;
}

export type ErrorCode =
  | 'NETWORK_ERROR'
  | 'API_KEY_INVALID'
  | 'API_QUOTA_EXCEEDED'
  | 'API_RATE_LIMITED'
  | 'DATABASE_ERROR'
  | 'NOT_FOUND'
  | 'VALIDATION_ERROR'
  | 'NOT_CONFIGURED'
  | 'UNKNOWN_ERROR';

export interface AskResult {
  question: Question;
  relatedQuestions: Question[];
  newConnections: number;
}

// ═══════════════════════════════════════════════════════════════════════════
// EVENT SYSTEM
// ═══════════════════════════════════════════════════════════════════════════

export type AppEvent =
  | { type: 'QUESTION_ASKED'; payload: Question }
  | { type: 'QUESTION_DELETED'; payload: { id: string } }
  | { type: 'CATEGORY_CREATED'; payload: Category }
  | { type: 'REVIEW_SUBMITTED'; payload: { questionId: string; rating: number } }
  | { type: 'REVIEW_DUE_COUNT_CHANGED'; payload: { count: number } }
  | { type: 'PLANNER_UPDATED'; payload: { reason: 'chunk' | 'thread' | 'checkin' } }
  | { type: 'PODCAST_GENERATION_STARTED'; payload: { podcastId: string; date: string } }
  | { type: 'PODCAST_GENERATION_PROGRESS'; payload: { podcastId: string; progress: number } }
  | { type: 'PODCAST_GENERATION_COMPLETED'; payload: DailyPodcast }
  | { type: 'PODCAST_GENERATION_FAILED'; payload: { podcastId: string; error: string } }
  | { type: 'LLM_CONFIG_CHANGED'; payload: LLMConfig }
  | { type: 'TTS_CONFIG_CHANGED'; payload: TTSConfig }
  | { type: 'ZEROTIER_STATUS_CHANGED'; payload: ZeroTierConfig }
  | { type: 'NETWORK_STATUS_CHANGED'; payload: { isOnline: boolean } }
  | { type: 'SESSION_CREATED'; payload: ChatSession }
  | { type: 'SESSION_UPDATED'; payload: { id: string } }
  | { type: 'FLASHCARDS_CREATED'; payload: { sessionId: string; count: number } };
