/**
 * Phase 10: Planner Auto-Suggestions Engine
 * Extended types for trajectory analysis, scoring, and auto-generated moves.
 */

// Re-export relevant types from main index for convenience
export type { PlannerChunk, ChunkType, ChunkStatus } from './index';

// ─── Trajectory Signal ─────────────────────────────────────────────────────

/**
 * Aggregated user learning signals used to score concept relevance.
 * All numeric fields are normalized to [0, 100] unless noted otherwise.
 */
export interface TrajectorySignal {
  /** Average correctness on due flashcards this week (0-100). Fallback: 50 if no cards. */
  reviewPerformance: number;
  /** Count of questions created in last 7 days. */
  questionFrequency: number;
  /** Milliseconds elapsed since the most overdue review. Fallback: 30 * 86400000 (30 days). */
  timeSinceLastReview: number;
  /** Feed engagement score (0-100). Placeholder for now — extended via event tracking later. */
  feedEngagement: number;
  /** Percentage of questions with at least 1 flashcard review (0-100). */
  conceptCoverage: number;
  /** Question IDs whose most recent review correctness was < 60% (SM-2 easeFactor < 2.5). */
  weakAreas: string[];
  /** Total completed reviews (used for cold-start detection). */
  completedReviews: number;
}

// ─── Scored Concept ────────────────────────────────────────────────────────

/** A concept ID with its computed relevance score after scoring. */
export interface ScoredConcept {
  id: string;
  score: number;
}

// ─── Planned Move ─────────────────────────────────────────────────────────

/** Move types for auto-generated suggestions. */
export type MoveType = 'review' | 'deepdive' | 'connection' | 'podcast';

/**
 * Auto-generated learning move. Extends PlannerChunk with auto-gen metadata.
 * Stored as a regular PlannerChunk in the planner service but carries
 * additional fields that mark it as auto-generated.
 */
export interface PlannedMove {
  // ── PlannerChunk base fields ──────────────────────────────────────────
  id: string;
  type: 'retrieve' | 'repair' | 'connect' | 'create';
  goal: string;
  description?: string;
  linkedConceptIds: string[];
  status: 'suggested' | 'in_progress' | 'saved_for_later' | 'done';
  createdAt: number;
  updatedAt: number;

  // ── Auto-gen extended fields ──────────────────────────────────────────
  /** Specific move sub-type for icon and description selection. */
  moveType: MoveType;
  /** Relevance score (0-100) computed by suggestionScorer. */
  relevanceScore: number;
  /** Optional link to a related resource (post, question, or review card). */
  linkedResource?: {
    type: 'post' | 'question' | 'review';
    id: string;
  };
  /** Always true for auto-generated moves — used to filter/clear suggestions. */
  isAutoGenerated: boolean;
}
